### ISSUE TITLE
function makeRequest() -- Two issues

### ISSUE THREAD

**Issue by johnabela** [spatie/last-fm-now-playing#6]
Hello,

Two things with your _makeRequest()_ function:

1. You really should be using **https:** and not **http:** 
2. There is a last.fm api variable called _**&nowplaying=true**_ that you can append that will query the currently _(now)_ playing song, if the user is currently playing a song, which you should consider adding to the URI.

**Comment by freekmurze** [comment]
Feel free to send a PR.
